### PR TITLE
Move t-shirt promption to the end

### PR DESCRIPTION
**Pull request by ButterCheezii**
Present this to visitors after they are satisfied rather than before. Related #50

### CODE REVIEW

**Comment by SachaG** [comment]
If you've seen that issue I'm not sure why you'd still take the time to submit this PR…

**Comment by ButterCheezii** [comment]
I thought you only took issue with the author's manner of speaking. It looks more like a personal attack than response to the problem.

I apologize for my misunderstanding

**Comment by SachaG** [comment]
Well, I definitely took issue with that person's tone and wording. But beyond that submitting a PR out of the blue just feels a bit passive aggressive… I mean, you know that I am perfectly capable of moving that page myself if I wanted to, so maybe the reason why that page is located where it is, is because I want it there? 

To me this feels a bit like submitting a PR to change someone site's font choices or color scheme. You're basically saying you know better than the maintainer, and so it shouldn't be a surprise if that kind of PR is not welcome.

**Comment by ButterCheezii** [comment]
Why did I submit it out of the blue? Because I wanted to make it easier for you, in case that you did want to have this change. I'm going to avoid trying to convince you, I only put this here just in case.

The intention wasn't to be passive aggressive, I tried to be as neutral as possible, so you could consider this change, without factoring my tone. Perhaps you're factoring the last submitter's tone instead and that's why you're acting like this.

But I'm never saying I know better than the maintainer, that's not the point at all. The point of pull requests is to contribute improvement, in any way. Why did I make one after seeing your behavior? You're right, I made a mistake, and overlooked it. Please excuse me, if this is how you treat everyone who posts here. Likewise, if you take your anger out on others.

**Comment by SachaG** [comment]
I'm not saying you had bad intentions, but I think there's this widespread misconception that any PR is good. The truth is that reviewing even a small PR like this one takes up the maintainer's time, and when (like this one) it provides such a tiny amount of value (I can literally make the change myself in less than five seconds, I don't need someone to do a PR) it's worth calling it out as a bad PR. 

PRs are just not a good system for decisions like this one. Again I don't have any ill will towards you and I'm sure you did it to be helpful, but in this case it wasn't.

**Pull request closed without merging**
